### ISSUE TITLE
Compilation error with 0.13.0

### ISSUE THREAD

**Issue by thibc81** [onbjerg/ethers-flashbots#49]
Hi

I get the following error when I compile ethers-flashbot 0.13.0 coming with the  ethers-signers v2.0.0 package.

15 |         ecdsa::{recoverable::Signature as RecoverableSignature, signature::DigestSigner},
   |                 ^^^^^^^^^^^ could not find `recoverable` in `ecdsa`

Note that ethers compile on its own without any issue.

Thanks!

**Comment by thibc81** [comment]
Solved by pointing to ethers = { git = "https://github.com/gakonst/ethers-rs"} in the toml but still issue with pointing to ethers' 2.0.0.

**Comment by ibhagwan** [comment]
@thibc81, try with the latest ethers-rs `2.0.6`, it compiles succesfully on my end.

There are other issues though with `2.0`, see #56.
